---
# Shared definition block
# This is where you would define any attributes that all your jobs will
# inherit. In our example, we state that all our Jobs will use the same Docker
# container for building in.
shared:
  # Docker image to use as the desired build container. This typically takes the
  # form of "repo_name". Alternatively, you can define the image as
  # "repo_name:tag_label".
  #
  # (Source: centos)
  image: centos:7
  steps:
    - init: git install

# Job definition block
# "main" is a default job that all pipelines have
jobs:
  # Jobs are defined by name.
  # All pipelines have "main" implicitly defined. The definitions in your
  # screwdriver.yaml file will override the implied defaults.
  main:
    # Requires is a single job name or array of job names that will trigger the job to run.
    # Jobs defined with "requires: ~pr" are started by pull-request events.
    # Jobs defined with "requires: ~commit" are started by push events.
    # Jobs defined with "requires: ~sd@123:main" are started by job "main" from pipeline "123".
    # Jobs defined with "requires: main" are started after "main" is done.
    # Jobs defined with "requires: [deploy-west, deploy-east] are started after "deploy-west" and "deploy-east" are both done running successfully.
    requires: [~pr, ~commit]
    # Steps is the list of commands to execute.
    steps:
      - install_git: hab pkg install core/git
      - print_yum: echo installing git and httpd service
      # - install_yum: yum -y install git httpd
      # Each step takes the form "step_name: command_to_run".
      # The "step_name" is a convenient label to reference it by. The
      # "command_to_run" is the single command that is executed during this
      # step. Environment variables will be passed between steps, within
      # the same job (as shown below).

  # We define another Job called "second_job". In this Job, we intend on running
  # a different set of commands.
  second_job:
    requires: main
    steps:
      # The "make_target" step calls a Makefile target to perform some set of
      # actions. This is incredibly useful when you need to perform a multi-line
      # command.
      # - cp_idx: copy index.html /var/www/html
      # - cp_err: copy err.html /var/www/html
      # - echo_idx: echo $HOSTNAME >> /var/www/html/index.html
      - print_start: echo Starting httpd service
      # - start_httpd: service httpd restart
      # - config_httpd: systemctl enable httpd.service
      # The "run_arbitrary_script" executes a script. This is an alternative to
      # a Makefile target where you want to run a series of commands related to
      # this step
      # - run_arbitrary_script: ./my_script.sh
